package com.fouryouandme.researchkit.task.video

import com.fouryouandme.researchkit.step.introduction.list.IntroductionItem

data class VideoTaskData(
    val introBackgroundColor: Int,
    val introFooterBackgroundColor: Int,
    val introTitle: String,
    val introTitleColor: Int,
    val introImage: Int,
    val introButton: String,
    val introButtonColor: Int,
    val introButtonTextColor: Int,
    val introList: List<IntroductionItem>,
    val introShadowColor: Int,
    val introToolbarColor: Int,
    val videoTitle: String,
    val videoTitleColor: Int,
    val videoRecordImage: Int,
    val videoPauseImage: Int,
    val videoPlayImage: Int,
    val videoFlashOnImage: Int,
    val videoFlashOffImage: Int,
    val videoCameraToggleImage: Int,
    val videoStartRecordingDescription: String,
    val videoStartRecordingDescriptionColor: Int,
    val videoTimeImage: Int,
    val videoTimeColor: Int,
    val videoTimeProgressBackgroundColor: Int,
    val videoTimeProgressColor: Int,
    val videoInfoTitle: String,
    val videoInfoTitleColor: Int,
    val videoInfoBody: String,
    val videoInfoBodyColor: Int,
    val videoReviewTimeColor: Int,
    val videoReviewButton: String,
    val videoSubmitButton: String,
    val videoButtonColor: Int,
    val videoButtonTextColor: Int,
    val videoInfoBackgroundColor: Int,
    val videoCloseImage: Int,
    val videoMissingPermissionCamera: String,
    val videoMissingPermissionCameraBody: String,
    val videoMissingPermissionMic: String,
    val videoMissingPermissionMicBody: String,
    val videoSettings: String,
    val videoCancel: String,
)