/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/square/retrofit
     */
    const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit
     */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val lifecycle_viewmodel_ktx: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val lifecycle_viewmodel_savedstate: String =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:" + Versions.androidx_lifecycle

    /**
     * https://github.com/square/moshi/
     */
    const val moshi_adapters: String = "com.squareup.moshi:moshi-adapters:" +
            Versions.com_squareup_moshi

    /**
     * https://github.com/square/moshi/
     */
    const val moshi_kotlin: String = "com.squareup.moshi:moshi-kotlin:" +
            Versions.com_squareup_moshi

    /**
     * https://github.com/arrow-kt/arrow/
     */
    const val arrow_fx: String = "io.arrow-kt:arrow-fx:" + Versions.io_arrow_kt

    /**
     * https://github.com/arrow-kt/arrow/
     */
    const val arrow_fx_coroutines: String = "io.arrow-kt:arrow-fx-coroutines:" +
            Versions.io_arrow_kt

    /**
     * https://github.com/arrow-kt/arrow/
     */
    const val arrow_meta: String = "io.arrow-kt:arrow-meta:" + Versions.io_arrow_kt

    /**
     * https://github.com/arrow-kt/arrow/
     */
    const val arrow_optics: String = "io.arrow-kt:arrow-optics:" + Versions.io_arrow_kt

    /**
     * https://github.com/arrow-kt/arrow/
     */
    const val arrow_syntax: String = "io.arrow-kt:arrow-syntax:" + Versions.io_arrow_kt

    const val moshi_jsonapi: String = "moe.banana:moshi-jsonapi:" + Versions.moe_banana

    const val moshi_jsonapi_retrofit_converter: String =
            "moe.banana:moshi-jsonapi-retrofit-converter:" + Versions.moe_banana

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val android_arch_lifecycle_extensions: String = "android.arch.lifecycle:extensions:" +
            Versions.android_arch_lifecycle_extensions

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/testing
     */
    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:" +
            Versions.androidx_test_ext_junit

    /**
     * http://junit.org
     */
    const val junit_junit: String = "junit:junit:" + Versions.junit_junit

    const val de_fayard_buildsrcversions_gradle_plugin: String =
        "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
                Versions.de_fayard_buildsrcversions_gradle_plugin

    const val firebase_crashlytics_gradle: String =
        "com.google.firebase:firebase-crashlytics-gradle:" +
                Versions.firebase_crashlytics_gradle

    const val firebase_crashlytics_ktx: String = "com.google.firebase:firebase-crashlytics-ktx:" +
            Versions.firebase_crashlytics_ktx

    const val firebase_analytics_ktx: String = "com.google.firebase:firebase-analytics-ktx:" +
            Versions.firebase_analytics_ktx

    const val firebase_messaging_ktx: String = "com.google.firebase:firebase-messaging-ktx:" +
            Versions.firebase_messaging_ktx

    /**
     * https://square.github.io/okhttp/
     */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.logging_interceptor

    const val recycler_droid_core: String = "com.giacomoparisi.recyclerdroid:recycler-droid-core:" +
            Versions.recycler_droid_core

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    const val google_services: String = "com.google.gms:google-services:" + Versions.google_services

    const val security_crypto: String = "androidx.security:security-crypto:" +
            Versions.security_crypto

    const val camera_camera2: String = "androidx.camera:camera-camera2:" + Versions.camera_camera2

    const val mpandroidchart: String = "com.github.PhilJay:MPAndroidChart:" +
            Versions.mpandroidchart

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * https://github.com/gcacace/android-signaturepad
     */
    const val signature_pad: String = "com.github.gcacace:signature-pad:" + Versions.signature_pad

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    const val camera_core: String = "androidx.camera:camera-core:" + Versions.camera_core

    const val camera_view: String = "androidx.camera:camera-view:" + Versions.camera_view

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/JakeWharton/ThreeTenABP/
     */
    const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" +
            Versions.threetenabp

    /**
     * https://github.com/giacomoParisi/span-droid
     */
    const val span_droid: String = "com.giacomoparisi.spandroid:span-droid:" + Versions.span_droid

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val viewpager2: String = "androidx.viewpager2:viewpager2:" + Versions.viewpager2

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://code.google.com/p/mp4parser/
     */
    const val isoparser: String = "com.googlecode.mp4parser:isoparser:" + Versions.isoparser

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://github.com/karumi/Dexter
     */
    const val dexter: String = "com.karumi:dexter:" + Versions.dexter

    /**
     * https://github.com/airbnb/lottie-android
     */
    const val lottie: String = "com.airbnb.android:lottie:" + Versions.lottie

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    const val toasty: String = "com.github.GrenderG:Toasty:" + Versions.toasty

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * https://github.com/hbb20/CountryCodePickerProject
     */
    const val ccp: String = "com.hbb20:ccp:" + Versions.ccp
}
