package org.fouryouandme.core.entity.configuration

data class Text(
    val errorTitleDefault: String,
    val errorMessageDefault: String,
    val errorButtonRetry: String,
    val errorButtonCancel: String,
    val errorMessageRemoteButton: String,
    val errorMessageConnectivity: String,
    val setupErrorTitle: String,
    val introTitle: String,
    val introBody: String,
    val introBack: String,
    val introLogin: String,
    val genericInfoTitle: String,
    val welcomeStartButton: String,
    val signUpLaterBody: String,
    val signUpLaterConfirmButton: String,
    val phoneVerificationTitle: String,
    val phoneVerificationBody: String,
    val phoneVerificationLegal: String,
    val phoneVerificationResendCode: String,
    val phoneVerificationWrongNumber: String,
    val phoneVerificationCodeDescription: String,
    val phoneVerificationErrorWrongCode: String,
    val phoneVerificationNumberDescription: String,
    val phoneVerificationErrorMissingNumber: String,
    val phoneVerificationLegalPrivacyPolicy: String,
    val phoneVerificationLegalTermsOfService: String
)